

services:
  alexpro-db:
    container_name: alexpro-db-container
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_DB: alexpro_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    networks:
      - pro-network
    volumes:
      - postgres_alexpro_data:/var/lib/postgresql/data

networks:
  unbrella-network:
    driver: bridge