server:
  port: 8090

spring:
  application:
    name: alexPro-backend

  datasource:
    url: jdbc:postgresql://localhost:5433/alexpro_db
    username: postgres
    password: "1234"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop #update quando si implementera gl'aggiornamenti
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Mantenuto il tuo limitatore di rate...
resilience4j.ratelimiter:
  instances:
    gateRateLimiter:
      limitForPeriod: 3
      limitRefreshPeriod: 1m
      timeoutDuration: 0s